config/routes.rb
Transport::Application.routes.draw do
  resources :categories

  resources :drivers

  resources :routes

  match "/error" => "drivers#error", :as => :error

   root :to => "drivers#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/route.rb
class Route < ActiveRecord::Base
  self.per_page = 20
  belongs_to :driver
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  # GET /routes
  # GET /routes.xml
  def index
    @routes = Route.paginate(:page=>params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @routes }
    end
  end

  # GET /routes/1
  # GET /routes/1.xml
  def show
    @route = Route.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/new
  # GET /routes/new.xml
  def new
    @route = Route.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @route }
    end
  end

  # GET /routes/1/edit
  def edit
    @route = Route.find(params[:id])
  end

  # POST /routes
  # POST /routes.xml
  def create
    @route = Route.new(params[:route])

    respond_to do |format|
      if @route.save
        format.html { redirect_to(@route, :notice => 'Route was successfully created.') }
        format.xml  { render :xml => @route, :status => :created, :location => @route }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /routes/1
  # PUT /routes/1.xml
  def update
    @route = Route.find(params[:id])

    respond_to do |format|
      if @route.update_attributes(params[:route])
        format.html { redirect_to(@route, :notice => 'Route was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @route.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.xml
  def destroy
    @route = Route.find(params[:id])
    @route.destroy

    respond_to do |format|
      format.html { redirect_to(routes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<center><h1>Список маршрутів</h1></center>

<center><table>
  <tr>
    <th>Номер</th>
    <th>Ім’я</th>
    <th>Ім’я водія</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @routes.each do |route| %>
  <tr>
    <td><%= route.number %></td>
    <td><%= route.name %></td>
    <td><%= route.driver.name%></td>
    <td><%= link_to 'Показати', route %></td>
    <td><%= link_to 'Редагувати', edit_route_path(route) %></td>
    <td><%= link_to 'Знищити', route, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%=will_paginate @routes%>
<%= link_to 'New Route', new_route_path %>
</center>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @route.number %>
</p>

<p>
  <b>Name:</b>
  <%= @route.name %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>