config/routes.rb
Transport::Application.routes.draw do
  resources :categories

  resources :drivers

  resources :routes

  match "/error" => "drivers#error", :as => :error

   root :to => "drivers#index"

   match ':controller(/:action(/:id(.:format)))'
end

app/models/driver.rb
class Driver < ActiveRecord::Base
 self.per_page  =  20
 has_many :routes
 belongs_to :category
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  # GET /drivers
  # GET /drivers.xml
  def index
    @drivers = Driver.paginate(:page=>params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @drivers }
    end
  end

  def error
  end
  
  # GET /drivers/1
  # GET /drivers/1.xml
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.xml
  def new
    @driver = Driver.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.xml
  def create
    @driver = Driver.new(params[:driver])

    respond_to do |format|
      if @driver.save
        format.html { redirect_to(@driver, :notice => 'Driver was successfully created.') }
        format.xml  { render :xml => @driver, :status => :created, :location => @driver }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @driver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.xml
  def update
    @driver = Driver.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to(@driver, :notice => 'Driver was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @driver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.xml
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to(drivers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Ім'я" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tel, "Телефон" %><br />
    <%= f.text_field :tel %>
  </div>
  <div class="field">
    <%= f.label :category_id, "Категорія"%><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit "Створити/Оновити"%>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Редагування водія</h1>

<%= render 'form' %>

<%= link_to 'Відобразити', @driver %> |
<%= link_to 'Список водіїв', drivers_path %>

app/views/drivers/error.html.erb
<p id="notice"><%= notice %></p>

app/views/drivers/index.html.erb
<center><h1>Список водіїв</h1></center>
<center><table>
  <tr>
    <th>Ім'я</th>
    <th>Номер телефону
    <th>Категорія</th>
    
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.name %></td>
    <td><%= driver.tel %></td>
    <td><%= driver.category.name %></td>
    <td><%= link_to 'Показати', driver %></td>
    <td><%= link_to 'Редагувати', edit_driver_path(driver) %></td>
    <td><%= link_to 'Знищити', driver, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />


<%= link_to 'Новий водій', new_driver_path %>
<br />
<%= will_paginate @drivers%>
</center>
</body>

app/views/drivers/new.html.erb
<h1>Новий водій</h1>

<%= render 'form' %>

<%= link_to 'Повернутись до списку', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ім'я:</b>
  <%= @driver.name %>
</p>

<p>
  <b>Телефон:</b>
  <%= @driver.tel %>
</p>

<p>
  <b>Категорія:</b>
  <%= @driver.category.name %>
</p>


<%= link_to 'Редагувати', edit_driver_path(@driver) %> |
<%= link_to 'Список водіїв', drivers_path %>